name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE $AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&@#'
exclude_labels:
  - 'skip-changelog'
template: |

  $CHANGES
