name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE `$AUTHOR` ([#$NUMBER]($URL))'
change-title-escapes: '\<*_&@'
exclude-labels:
  - 'skip-changelog'
template: |

  $CHANGES
