name: "Draft or update release"
on:
  push:
    branches:
      - trunk

jobs:
  update_release_draft:
  
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    
    steps:
      - name: "[Setup] - .NET Core"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: "[Setup] - Install GitVersion"
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.10.3'

      - name: "[Setup] - Install GitReleaseManager"
        uses: gittools/actions/gitreleasemanager/setup@v0.9.13
        with:
          versionSpec: '0.13.0'
      
      - name: "[Draft Release] - Create/Update GitHub Release ${{ steps.gitversion.outputs.majorMinorPatch }}"
        run: |
          dotnet-gitreleasemanager create --owner edwinkortman --repository studious-funicular --token ${{ secrets.GITHUB_TOKEN }}
